### ISSUE TITLE
Incorrect information in README.md

### ISSUE THREAD

**Issue by amberjennings** [kotlin-hands-on/advent-of-code-kotlin-template#34]
FILE: README.md
CONTEXT: "...a programming puzzles contest is published every day for twenty-four days."
SUGGESTED CHANGE: Advent of Code is 25 days long, may want to replace twenty-four with twenty-five.

From [adventofcode.com/2023/day1]() (most recent event):

> "You've been doing this long enough to know that to restore snow operations, you need to check all fifty stars by December 25th.
> 
> Collect stars by solving puzzles. Two puzzles will be made available on each day in the Advent calendar; the second puzzle is unlocked when you complete the first. Each puzzle grants one star. Good luck!"

From [adventofcode.com/2015/day1]() (first event):

> "Santa was hoping for a white Christmas, but his weather machine's "snow" function is powered by stars, and he's fresh out! To save Christmas, he needs you to collect fifty stars by December 25th.
> 
> Collect stars by helping Santa solve puzzles. Two puzzles will be made available on each day in the Advent calendar; the second puzzle is unlocked when you complete the first. Each puzzle grants one star. Good luck!"

**Comment by amberjennings** [comment]
I didn't think this minor issue warranted a fork + PR, but if this is incorrect, I am happy to go through that process.

**Comment by hsz** [comment]
Thanks!
