### ISSUE TITLE
Template should hide input files by default

### ISSUE THREAD

**Issue by jpd236** [kotlin-hands-on/advent-of-code-kotlin-template#4]
Thanks for providing this template!

Noticed this tweet from the AoC maintainer while I was setting up: https://twitter.com/ericwastl/status/1465805354214830081

"In general I ask people not to publish their inputs, just to make it harder for someone to try to steal the whole site."

This template encourages putting in actual inputs into the DayNN.txt files and committing them to the repository. Perhaps the input files should be added to .gitignore and/or moved to a separate folder to discourage this from happening (at least for future uses of this template).

**Comment by hsz** [comment]
That's a good point, on it.
