### ISSUE TITLE
Template does not work in Android Studio

### ISSUE THREAD

**Issue by johnwilde** [kotlin-hands-on/advent-of-code-kotlin-template#7]
Thanks for making the template! However it does not appear to run when using Android Studio Arctic Fox, although IntelliJ CE does work. 

Can you help me get it working in that IDE?

**Comment by LARALK** [comment]
OLA EM QUE POSSO AJUDAR

**Comment by hsz** [comment]
Thanks, John!
To run the specific day, open a desired file and click on the green Run arrow:
<img width="598" alt="image" src="https://user-images.githubusercontent.com/108333/144812196-e2a0df5b-8c04-422a-b929-d284d0a59170.png">
