### ISSUE TITLE
Please delete PR 8

### ISSUE THREAD

**Issue by alysyk** [kotlin-hands-on/advent-of-code-kotlin-template#9]
Hi Team,

Thank you for creating this template!

Unfortunately, I forked the template rather than created a new project from it and submitted a solution PR to the repo. Old habits die hard. Can you please delete the PR? https://github.com/kotlin-hands-on/advent-of-code-kotlin-template/pull/8

Thanks!

**Comment by hsz** [comment]
Andrew, unfortunately, it's not possible to delete pull requests, even for the repository owner.
However, you can get back to your branch, reset it before your commit and push force it.
That should clear your PR.

P.S. I'm pleased you like this Template. ☺️

**Comment by alysyk** [comment]
Apologies. I've deleted the fork so this PR seems to be hanging. I believe the maintainer can use the GitHub support to delete a PR.
